@startuml
(*) --> "Инициализация БД"
--> "Запрос курсов валют (ЦБ РФ)"
if "Успешно?" then
  -->[да] "Сохранение курсов в БД"
  --> "Обход списка источников"
else
  -->[нет] "Логирование ошибки"
  --> "Обход списка источников"
endif

partition "Цикл по товарам" {
  "Обход списка источников" --> "Потоковый парсинг (iterparse)"
  --> "Нормализация данных"
  --> "Конвертация валют"
  --> "Сохранение (Upsert)"
}

if "Есть еще источники?" then
  -->[да] "Обход списка источников"
else
  -->[нет] "Завершение транзакции"
  --> "Ожидание (1 час)"
  --> "Запрос курсов валют (ЦБ РФ)"
endif
@enduml


