@startuml
node "Устройство пользователя" as Client {
    artifact "Telegram App"
}

node "Сервер VPS (Linux)" as Server {
    node "Docker Engine" {
        component "Bot Container" as Bot
        component "Collector Container" as Coll
        database "PostgreSQL" as DB
    }
}

cloud "Telegram Cloud" as TG
cloud "Источники (API/YML)" as Web

Client -- TG : HTTPS
TG -- Bot : HTTPS (Long Polling)
Bot -- DB : SQL (Port 5432)
Coll -- DB : SQL (Port 5432)
Coll -- Web : HTTP/XML
@enduml


