@startmindmap
* Система мониторинга цен
** Функциональность
*** Сбор данных (ETL)
**** ЦБ РФ (курсы)
**** YML-фиды
**** XLS-прайсы
*** Анализ
**** Сравнение цен
**** Поиск товаров
**** Статистика
*** Интерфейс
**** Telegram Бот
** Технологии
*** Язык: Python 3.11
*** БД: PostgreSQL
*** Контейнеры: Docker
** Архитектура
*** Распределенная
*** Микросервисная
*** Асинхронная
@endmindmap


